### ISSUE TITLE
Create credential secret from OC SDK

### ISSUE THREAD

**Issue by kberkos-public** [IBM/operator-collection-sdk#3]
#### Describe the problem you need a feature to resolve.
Currently, when users are trying to create a credential secret in an airgapped environment (without access to github or other sources) creating the secret is very difficult.

#### Describe the solution you'd like.
I'd like to be able to run a playbook that will exec into the ansible pod and create the credential secret for me automatically.

**Comment by freemanlatrell** [comment]
It would be nice if the playbook can accept the same parameters as the `zoscb-encrypt` CLI so that it's not a huge distinction between the two.

Things to consider:
- Need to determine the best way to locate the correct suboperator pod to exec into. You may need to accept an additional parameter called `operator_name` which you should then be able to retrieve this pod using the `operator-name` label. This isn't needed for all other playbooks in this collection since we are able to determine this by the `operator-config` file in the root directory....but users of this playbook will not have access to the `operator-config` for this operator
- Validate that the `zoscb-encrypt` CLI exists inside the pod. This won't exist for previous releases of the broker
