### ISSUE TITLE
Permission Denied error when running ansible-galaxy collection install command

### ISSUE THREAD

**Issue by farrart** [IBM/operator-collection-sdk#7]
#### What did you do?

I ran the following command on the vm I am installing the tool on:
     `ansible-galaxy collection install git@github.com:IBM/operator-collection-sdk.git#ibm/operator_collection_sdk,v0.x -f`

#### What did you expect to see?

I expected for the install to complete successfully

#### What did you see instead? Under which circumstances?

it returned the following error:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

#### Collection Version

`$ ansible-galaxy collection verify ibm.operator_collection_sdk`

ibm.operator_collection_sdk:0.2.0

#### Additional context

![image](https://github.com/IBM/operator-collection-sdk/assets/38953320/9c58effd-0f63-4349-894d-e4ceac059b4e)

**Comment by freemanlatrell** [comment]
This is due to the default install command using the SSH git command instead of HTTPS. If a user hasn't uploaded a public key to their Github account then the following error occurs. This has now been resolved by updating the install command to use HTTPS https://github.com/IBM/operator-collection-sdk/commit/d66875ff427752943d61ec14eb154f0298c30f38

```
ansible-galaxy collection install git+https://github.com/IBM/operator-collection-sdk.git#ibm/operator_collection_sdk -f
```
